/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakvimRouteImport } from './routes/takvim'
import { Route as KartlarimRouteImport } from './routes/kartlarim'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as IndexRouteImport } from './routes/index'

const TakvimRoute = TakvimRouteImport.update({
  id: '/takvim',
  path: '/takvim',
  getParentRoute: () => rootRouteImport,
} as any)
const KartlarimRoute = KartlarimRouteImport.update({
  id: '/kartlarim',
  path: '/kartlarim',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/kartlarim': typeof KartlarimRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/kartlarim': typeof KartlarimRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayarlar': typeof AyarlarRoute
  '/kartlarim': typeof KartlarimRoute
  '/takvim': typeof TakvimRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ayarlar' | '/kartlarim' | '/takvim'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ayarlar' | '/kartlarim' | '/takvim'
  id: '__root__' | '/' | '/ayarlar' | '/kartlarim' | '/takvim'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyarlarRoute: typeof AyarlarRoute
  KartlarimRoute: typeof KartlarimRoute
  TakvimRoute: typeof TakvimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/takvim': {
      id: '/takvim'
      path: '/takvim'
      fullPath: '/takvim'
      preLoaderRoute: typeof TakvimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kartlarim': {
      id: '/kartlarim'
      path: '/kartlarim'
      fullPath: '/kartlarim'
      preLoaderRoute: typeof KartlarimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyarlarRoute: AyarlarRoute,
  KartlarimRoute: KartlarimRoute,
  TakvimRoute: TakvimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
